version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperGeek12345
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - 1433:1433
