version: "3.8"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: SuperGeek
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: ./SuperGeek
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./key:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    ports:
      - 5000:5000

  front:
    build: ./front
    restart: always
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - api
    ports:
      - 3000:80