version: "3.8"
services:
  api:
    build: "./SuperGeek"
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./key:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperGeek12345
    volumes:
      - ./db:/var/opt/mssql/data
    ports:
      - 1433:1433

  front:
    build: "./front"
    restart: always
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - api
    ports:
      - 3000:80